import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { configureImageSettings } from "imagined";
import "./globals.css";

// Configure imagined to match the config file settings
configureImageSettings({
  publicPath: "/generated-images",
  imageFormat: "jpg",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
